#!/bin/bash

current_dir=$(pwd)
echo $current_dir
cd sources/
# Get the list of modified .java files
modified_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.java')

if [[ -n $modified_files ]]; then
    # Execute the Maven Checkstyle plugin on the modified .java files
    echo "Checking files:"
    echo $modified_files

    # Iterate through the files
    while IFS= read -r file; do
        echo "Checking: "$(basename "$file")""
        mvn checkstyle:check -Dcheckstyle.includes="**/$(basename "$file")"

        # Checking the output
        checkstyle_exit_code=$?
        if [[ $checkstyle_exit_code -ne 0 ]]; then
            echo "Checkstyle violations detected, please fix them!"
            exit 1
        fi
    done <<< "$modified_files"
fi

cd "$current_dir"

exit 0